### Import Required Packages

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

/usr/local/lib/python3.10/dist-packages/matplotlib/projections/__init__.py:63: UserWarning: Unable to import Axes3D. This may be due to multiple versions of Matplotlib being installed (e.g. as a system package and as a pip package). As a result, the 3D projection is not available.
  warnings.warn("Unable to import Axes3D. This may be due to multiple versions of "


### Load the data

In [2]:
df = pd.read_csv('./Pro5.csv')
df

airline  overall  traveller_type           cabin  seat_comfort  \
0           71        7        Business   Economy Class           4.0   
1           71        2  Family Leisure   Economy Class           4.0   
2           71        3        Business   Economy Class           1.0   
3           71       10    Solo Leisure   Economy Class           4.0   
4           71        1    Solo Leisure   Economy Class           1.0   
...        ...      ...             ...             ...           ...   
65942       72        5  Couple Leisure   Economy Class           3.0   
65943       72        5  Couple Leisure  Business Class           1.0   
65944       72        4    Solo Leisure  Business Class           4.0   
65945       72        7  Couple Leisure  Business Class           1.0   
65946       72        4    Solo Leisure   Economy Class           1.0   

       cabin_service  food_bev  entertainment  ground_service  \
0                5.0       4.0              4               2   
1                1.0       1.0              1               1   
2                4.0       1.0              3               1   
3                5.0       5.0              5               5   
4                1.0       1.0              1               1   
...              ...       ...            ...             ...   
65942            5.0       4.0              1               5   
65943            5.0       1.0              3               2   
65944            1.0       2.0              2               3   
65945            5.0       4.0              2               4   
65946            5.0       5.0              4               1   

       value_for_money  recommended  Customer_reviews_nlp  
0                    4            1                     1  
1                    1            0                     1  
2                    2            0                     1  
3                    5            1                     1  
4                    1            0                     1  
...                ...          ...                   ...  
65942                2            0                     1  
65943                2            0                     1  
65944                3            0                     1  
65945                3            0                     0  
65946                2            0                     1  

[65947 rows x 12 columns]

In [3]:
df.isna().sum()

airline                 0
overall                 0
traveller_type          0
cabin                   0
seat_comfort            0
cabin_service           0
food_bev                0
entertainment           0
ground_service          0
value_for_money         0
recommended             0
Customer_reviews_nlp    0
dtype: int64

In [4]:
from sklearn.preprocessing import LabelEncoder

encoder_traveller_type = LabelEncoder()
df['traveller_type'] = encoder_traveller_type.fit_transform(df['traveller_type'])

In [5]:
df

airline  overall  traveller_type           cabin  seat_comfort  \
0           71        7               0   Economy Class           4.0   
1           71        2               2   Economy Class           4.0   
2           71        3               0   Economy Class           1.0   
3           71       10               3   Economy Class           4.0   
4           71        1               3   Economy Class           1.0   
...        ...      ...             ...             ...           ...   
65942       72        5               1   Economy Class           3.0   
65943       72        5               1  Business Class           1.0   
65944       72        4               3  Business Class           4.0   
65945       72        7               1  Business Class           1.0   
65946       72        4               3   Economy Class           1.0   

       cabin_service  food_bev  entertainment  ground_service  \
0                5.0       4.0              4               2   
1                1.0       1.0              1               1   
2                4.0       1.0              3               1   
3                5.0       5.0              5               5   
4                1.0       1.0              1               1   
...              ...       ...            ...             ...   
65942            5.0       4.0              1               5   
65943            5.0       1.0              3               2   
65944            1.0       2.0              2               3   
65945            5.0       4.0              2               4   
65946            5.0       5.0              4               1   

       value_for_money  recommended  Customer_reviews_nlp  
0                    4            1                     1  
1                    1            0                     1  
2                    2            0                     1  
3                    5            1                     1  
4                    1            0                     1  
...                ...          ...                   ...  
65942                2            0                     1  
65943                2            0                     1  
65944                3            0                     1  
65945                3            0                     0  
65946                2            0                     1  

[65947 rows x 12 columns]

In [6]:
df['traveller_type'].unique()

array([0, 2, 3, 1])

In [7]:
encoder_cabin = LabelEncoder()
df['cabin'] = encoder_cabin.fit_transform(df['cabin'])

In [8]:
df

airline  overall  traveller_type  cabin  seat_comfort  cabin_service  \
0           71        7               0      1           4.0            5.0   
1           71        2               2      1           4.0            1.0   
2           71        3               0      1           1.0            4.0   
3           71       10               3      1           4.0            5.0   
4           71        1               3      1           1.0            1.0   
...        ...      ...             ...    ...           ...            ...   
65942       72        5               1      1           3.0            5.0   
65943       72        5               1      0           1.0            5.0   
65944       72        4               3      0           4.0            1.0   
65945       72        7               1      0           1.0            5.0   
65946       72        4               3      1           1.0            5.0   

       food_bev  entertainment  ground_service  value_for_money  recommended  \
0           4.0              4               2                4            1   
1           1.0              1               1                1            0   
2           1.0              3               1                2            0   
3           5.0              5               5                5            1   
4           1.0              1               1                1            0   
...         ...            ...             ...              ...          ...   
65942       4.0              1               5                2            0   
65943       1.0              3               2                2            0   
65944       2.0              2               3                3            0   
65945       4.0              2               4                3            0   
65946       5.0              4               1                2            0   

       Customer_reviews_nlp  
0                         1  
1                         1  
2                         1  
3                         1  
4                         1  
...                     ...  
65942                     1  
65943                     1  
65944                     1  
65945                     0  
65946                     1  

[65947 rows x 12 columns]

In [9]:
df['airline'].unique()

array([71, 54, 31, 49, 44, 74, 17, 28, 62, 73, 43,  2,  4,  5,  7, 13, 16,
       14, 18, 20, 19, 22, 23, 25, 26, 27, 32, 30, 35, 40,  0, 79, 45, 47,
       48, 52, 11, 33, 51, 56, 57, 61, 59, 66, 34, 29, 55, 60, 58, 65, 68,
       12, 10,  8, 78,  9, 24, 77, 63, 67, 75, 64, 53, 21, 80, 37, 38, 36,
       41, 42,  3,  1,  6, 15, 70, 50, 69, 39, 46, 76, 72])

In [10]:
df['cabin'].unique()

array([1, 0, 2, 3])

In [11]:
df.to_csv('Project.csv')